name: Verify Keystore

on:
  push:
    branches: ["gradle"]
  workflow_dispatch:

jobs:
  check-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if KEYSTORE_FILE secret is empty
        run: |
          if [ -z "${{ secrets.KEYSTORE_FILE }}" ]; then
            echo "Keystore secret is empty. Exiting..."
            exit 1
          fi

      - name: Restore Keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > mg-build-release-key.keystore

      - name: Verify Keystore File Size
        run: |
          if [ ! -s mg-build-release-key.keystore ]; then
            echo "Keystore file is empty. Exiting..."
            exit 1
          fi

      - name: List Keystore Contents
        run: |
          keytool -list -v -keystore mg-build-release-key.keystore -storepass "${{ secrets.KEYSTORE_PASSWORD }}"
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64  # Ensure Java is available

      - name: Clean up
        run: |
          rm mg-build-release-key.keystore
