name: Hugo Build and Publish

on:
  push:
    branches:
      - gradle

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo
        run: hugo --minify

      - name: Publish to gradle/public
        run: |
          mkdir -p gradle/public
          cp -r public/* gradle/public/  # Copy generated files to gradle/public

      - name: List published files
        run: ls -la gradle/public  # List contents for debugging