name: Hugo Build and Publish

on:
  push:
    branches:
      - gradle

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Hugo
        run: hugo --minify

      - name: Publish to public
        run: |
          mkdir -p public
          cp -r public/* public/  # Copy generated files to public

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public
          git commit -m "Update static site content"
          git push origin gradle  # Push changes to the gradle branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}