name: Verify Keystore

on:
  push:
    branches: ["gradle"]
  workflow_dispatch:

jobs:
  check-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > mg-build-release-key.keystore

      - name: Check Directory Contents and Keystore Size
        run: |
          echo "Listing current directory contents:"
          ls -la

          echo "Checking the size of the keystore file:"
          if [ -s mg-build-release-key.keystore ]; then
            echo "Keystore file is not empty. Size:"
            du -h mg-build-release-key.keystore
          else
            echo "Keystore file is empty."
            exit 1  # Fail the workflow if the file is empty
          fi

      - name: List Keystore Contents
        run: |
          keytool -list -v -keystore mg-build-release-key.keystore -storepass "${{ secrets.KEYSTORE_PASSWORD }}"
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64  # Ensure Java is available

      - name: Clean up
        run: |
          rm mg-build-release-key.keystore
